import type { jsPDF } from "jspdf";
import type { GarmentDescription } from "@/types/garment";
import type { BodyMeasurements } from "@/types/measurements";
import { MEASUREMENT_LABELS, UPPER_BODY_KEYS, LOWER_BODY_KEYS } from "@/types/measurements";
import type { PatternPieceData } from "@/data/pattern-pieces";
import { MARGIN, PRINTABLE_WIDTH, FONT } from "./constants";
import type { FabricLayout } from "./fabric-layout";

/**
 * Render the cover page with garment info, measurements, piece inventory,
 * and fabric requirements.
 */
export function renderCoverPage(
  doc: jsPDF,
  garmentDescription: GarmentDescription,
  measurements: BodyMeasurements,
  pieces: PatternPieceData[],
  fabricLayout: FabricLayout,
): void {
  let y = MARGIN + 0.3;

  // --- Title ---
  doc.setFontSize(FONT.title);
  doc.setTextColor(0, 0, 0);
  doc.text("Check-Fit Sewing Pattern", MARGIN, y);
  y += 0.5;

  // --- Category badge + summary ---
  doc.setFontSize(FONT.subtitle);
  doc.setTextColor(60, 60, 60);
  const categoryLabel = garmentDescription.category.charAt(0).toUpperCase() + garmentDescription.category.slice(1);
  doc.text(`${categoryLabel} — ${garmentDescription.summary}`, MARGIN, y);
  y += 0.6;

  // --- Measurements table ---
  doc.setFontSize(FONT.body);
  doc.setTextColor(0, 0, 0);
  doc.text("Body Measurements", MARGIN, y);
  y += 0.1;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.005);
  doc.line(MARGIN, y, MARGIN + PRINTABLE_WIDTH, y);
  y += 0.2;

  // Two-column layout: upper body on left, lower body on right
  const colWidth = PRINTABLE_WIDTH / 2 - 0.2;
  const leftCol = MARGIN;
  const rightCol = MARGIN + PRINTABLE_WIDTH / 2 + 0.2;

  doc.setFontSize(FONT.small);
  doc.setTextColor(100, 100, 100);
  doc.text("Upper Body", leftCol, y);
  doc.text("Lower Body", rightCol, y);
  y += 0.25;

  doc.setFontSize(FONT.body);
  doc.setTextColor(0, 0, 0);

  const maxRows = Math.max(UPPER_BODY_KEYS.length, LOWER_BODY_KEYS.length);
  for (let i = 0; i < maxRows; i++) {
    if (i < UPPER_BODY_KEYS.length) {
      const key = UPPER_BODY_KEYS[i];
      const label = MEASUREMENT_LABELS[key];
      const value = measurements[key];
      doc.text(label, leftCol, y);
      doc.text(`${value}"`, leftCol + colWidth, y, { align: "right" });
    }
    if (i < LOWER_BODY_KEYS.length) {
      const key = LOWER_BODY_KEYS[i];
      const label = MEASUREMENT_LABELS[key];
      const value = measurements[key];
      doc.text(label, rightCol, y);
      doc.text(`${value}"`, rightCol + colWidth, y, { align: "right" });
    }
    y += 0.22;
  }

  y += 0.3;

  // --- Piece inventory table ---
  doc.setFontSize(FONT.body);
  doc.setTextColor(0, 0, 0);
  doc.text("Pattern Pieces", MARGIN, y);
  y += 0.1;

  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, MARGIN + PRINTABLE_WIDTH, y);
  y += 0.2;

  // Table header
  doc.setFontSize(FONT.small);
  doc.setTextColor(100, 100, 100);
  doc.text("Name", MARGIN, y);
  doc.text("Cut", MARGIN + 3.5, y);
  doc.text("Fold", MARGIN + 4.3, y);
  doc.text("Notes", MARGIN + 5.0, y);
  y += 0.05;
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, MARGIN + PRINTABLE_WIDTH, y);
  y += 0.2;

  doc.setFontSize(FONT.body);
  doc.setTextColor(0, 0, 0);

  for (const piece of pieces) {
    doc.text(piece.name, MARGIN, y);
    doc.text(String(piece.cutCount), MARGIN + 3.5, y);
    doc.text(piece.cutOnFold ? "Yes" : "No", MARGIN + 4.3, y);
    // Truncate instructions to fit
    const maxNoteWidth = PRINTABLE_WIDTH - 5.0;
    const note = piece.instructions.length > 60 ? piece.instructions.slice(0, 57) + "..." : piece.instructions;
    doc.text(note, MARGIN + 5.0, y, { maxWidth: maxNoteWidth });
    y += 0.22;
  }

  y += 0.3;

  // --- Fabric requirements ---
  doc.setFontSize(FONT.body);
  doc.setTextColor(0, 0, 0);
  doc.text("Fabric Requirements", MARGIN, y);
  y += 0.1;

  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, MARGIN + PRINTABLE_WIDTH, y);
  y += 0.25;

  doc.setFontSize(FONT.body);
  doc.text(`Fabric width: ${fabricLayout.fabricWidth}"`, MARGIN, y);
  y += 0.22;
  doc.text(`Yardage needed: ${fabricLayout.fabricYards} yard(s)`, MARGIN, y);
  y += 0.22;
  doc.text("Layout: Folded in half, selvage to selvage", MARGIN, y);
  y += 0.22;
  doc.text("Seam allowance: 5/8\" (included in pattern pieces)", MARGIN, y);
  y += 0.5;

  // --- Footer ---
  doc.setFontSize(FONT.label);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Check-Fit", MARGIN, 10.5);
}
